### ISSUE TITLE
Banner

### ISSUE THREAD

**Issue by ssbittle** [prenda-school/prenda-spark#149]
### Variations:
**Types**: Info, Success, Warning, Error
**Sizes**: One

**Design reference:**
[Figma file - Banner](https://www.figma.com/file/y6Ca8BdJtQEd3Of1saRieF/Spark-Design-System-Web?node-id=665%3A2)

**Comment by WilliamKelley** [comment]
### Feedback
@ssbittle 
Similar to others, can you decide if Spark wants to prescribe a Transition for Banner? See all ready-made [Transitions here](https://material-ui.com/components/transitions/)

### Implementation
Almost dentical implementation story to SectionMessage in #151 .

Except, corresponding variant is `"filled"` and obvious styling / placement differences in our stories.

**Comment by ssbittle** [comment]
@WilliamKelley Not sure if banners will need a transition, but Fade seems like the best option if we decided to use one. I lean towards no transition. Thoughts?

**Comment by WilliamKelley** [comment]
> @WilliamKelley Not sure if banners will need a transition, but Fade seems like the best option if we decided to use one. I lean towards no transition. Thoughts?

Considering the before, during and after of a banner appear above the whole page, it will shift all the content down immediately when it appears. That could be a jarring UX. The Collapse transition seems like the only appropriate one where it un-collapses from whatever side of the screen it touches, and the page smoothly makes way for it.

We'll have to see what the options look like in implementation, but the rest seem to need the full height space immediately in order to be reasonable

**Comment by ssbittle** [comment]
Good point. I was trying to find an example in the wild. But let's just see how it works in implementation. Good with that.
