### ISSUE TITLE
Section Message

### ISSUE THREAD

**Issue by ssbittle** [prenda-school/prenda-spark#151]
### Variations:
**Types**: Info, Success, Warning, Error

**Design reference:**
[Figma file - Section message](https://www.figma.com/file/y6Ca8BdJtQEd3Of1saRieF/Spark-Design-System-Web?node-id=2379%3A4207)

**Comment by WilliamKelley** [comment]
### Feedback
Similar to Tooltip and Popover, can you decide if Spark wants to prescribe a Transition for Section Message? See all ready-made [Transitions here](https://material-ui.com/components/transitions/)

### Implementation
Clear Mui parallel, [Alert](https://material-ui.com/components/alert) (and AlertTitle).

Corresponding variant is `"standard"` Action can be given through `action` prop (shouldn't set by default though since consumer needs to decide final behavior, but we can show in story). Do need to set our custom `iconMapping`.

Should also have a story mimicking [this one with a transition](https://material-ui.com/components/alert/#transition)

**Comment by ssbittle** [comment]
@WilliamKelley Same comment as banners.
