### ISSUE TITLE
Some spark icons have invalid `path` attributes

### ISSUE THREAD

**Issue by seigler** [prenda-school/prenda-spark#183]
Some path attributes in `spark-icons` are hyphenated instead of camelCased, producing React errors.

BeakerDuotone is one example:
> Warning: Invalid DOM property `stroke-linecap`. Did you mean `strokeLinecap`?

**Comment by WilliamKelley** [comment]
Interesting, all are desingers' custom icons, so i assume there's some standards that they dont adhere to like the rest of the library.

@alecdanz Tagging you because spencer is out (i think?). We've historically had issues standardizing custom icons in Figma so that they have a nice SVG export output. The icon library that was chosen does the best job i've seen so far at solving this. However, these custom icons are leaving some undesirable attributes related to stroke cap and width. Do you have experience in this area or thoughts on how to resolve this before exporting from Figma?

**Comment by alecdanz** [comment]
Hey sorry, missed the message yesterday. 

I think that it has something to do with the designer not adding a union onto the icon itself. 

Is it rendering correctly when you chance that to camelCase?

**Comment by WilliamKelley** [comment]
Sorry, i should have clarified, I'm not asking for the attributes to be exported camel-cased, the format of the attributes coming out of Figma is always standard syntax and that's _good_.

My request was that these specific attributes not appear _at all_ in the exported SVG. Any attribute that starts with `stroke-` does not appear in all of the other icons, except the custom ones created by the designers. And their presence is bad for us on the implementation side.
