### ISSUE TITLE
Would it be better to remove the Prenda Spark Theme Provider?

### ISSUE THREAD

**Issue by haase1020** [prenda-school/prenda-spark#41]
Currently, if you use a Prenda Spark component you need to wrap each component in the Prenda Spark Theme Provider. Would it be easier if that theme provider was removed?

**Comment by WilliamKelley** [comment]
There needs to be some clarification: to use a spark component, you need to _at minimum_ wrap that component in the theme provider, or _at most_ wrap your entire app in the provider. 

Even though I've described the latter as "at most", it's actually the easier option because it's one import and usage rather than for every component individually.

But I understand that wrapping the entire app is not feasible for an application using the default or core MUI theme/provider and can't completely switch to Spark outright. Substituting those for Spark's provider doesn't produce the right results outright because Spark requires customizing component implementation's outside design and theme possibilities.

For that situation and the current state of this library, it would be easier if the provider is removed for now. But for other situations and for in the future, that may not be the best choice.

There are a few remedies:
1. Deprecate SparkThemeProvider for now
    - At present, our components could receive the theme through a simple module import instead of through context.
    - In the future though, if/when spark supports multiple themes like light/dark and modes like RTL text, the ThemeProvider would become necessary again. So, we shouldn't disregard it's future use.
2. Change Spark's muiTheme to be more default-MUI friendly. 
    - The desired result: an application using the default/core MUI theme/provider could swap it outright with SparkThemeProvider. MUI Core components that aren't from Spark will either look like default (2a), or with an "okay" semblance of Spark (2b) -- it would depend on the items below.
    - I think we have a better idea now of the "trouble areas" we had with initially making a muiTheme. Things like the `light`, `main`, `dark` values that could fit Spark, given that many designs are finished now. Whereas before, there was _no_ clear way to tell what those values might best be. => (2a)
    - If we still can't find a way to improve default compatibility with Spark color / theme values and default components, then our theme values should use completely custom properties off `theme` so the MUI internals can set the correct defaults. => (2b)

-----

I think it's reasonable to say we'd accept a PR that implemented remedy 1, given that it's been talked about informally for a couple weeks now.
