### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by ssbittle** [prenda-school/prenda-spark#54]
## 🔥 Changes:
Each menu item is now consistently 40px in height and now support avatars

**Design reference:**
[Figma file - Menu](https://www.figma.com/file/y6Ca8BdJtQEd3Of1saRieF/Spark-Design-System-Web?node-id=668%3A175)

**Comment by WilliamKelley** [comment]
## Feedback

@ssbittle 
- In the Anatomy block, point out "Divider" this leads into the "sectioned" bit of the Component block.
- In the States block, a "focus" state is missing

## Assessment

### Anatomy
 ```tsx
<Menu> // "Container"
  <MenuItemDivider> // "Divider" [Optional] [Suggested]
  <MenuItem> // "Menu Item"
    <ListItemIcon> // "Leading Icon" [Optional]
      <Icon/>
    </ListItemIcon>
    <Typography> // "Label"
      Label
    </Typography>
  </MenuItem>
</Menu>
```

[From MUI Menu](https://material-ui.com/components/menus/#menus): Menu, MenuItem, ListItemIcon
- The name 'ListItemIcon' could be customized to 'MenuItemIcon', or it could be kept as it's general for it's eventual use to a List component that's suitable for always displayed list items, like in a Sidebar. After all, MenuItem is a ListItem with custom accessibility and function to appear as a triggered menu descendant. 

Already in Spark: Typography (DropdownMenu, DropdownMenuItem)

### Details (variants, composition, etc)
- Checkboxes
  - only fit for use in `Select` form menus, with multiple set, since it displays a form state (checked, unchecked, disabled) that needs to be interactive
    - afaik, the general term for this is "[Multi-Select Checkbox](https://www.google.com/search?q=multi+select+checkbox)"
  - Overall it's a more complicated pattern than it may seem at first, because a checkbox input element cannot appear as a descendant of option element in a multi-select element
  - But MUI has a [prepared solution](https://material-ui.com/components/autocomplete/#checkboxes) under the `<Autocomplete />` component.
    - We'll be able to exactly reuse the implemented `Checkbox` component
    - The Autocomplete doesn't reuse Menu / MenuItem from what I can tell, instead we'd have to style relevant class names like `MuiAutocomplete-listbox` and `MuiAutocomplete-option` similarly to Menu, MenuItem
![image](https://user-images.githubusercontent.com/25781782/120690305-09d26a80-c473-11eb-9d18-348f4384f0b1.png)

- Avatar
  - should either take the place of `<ListItemIcon />` since the MUI Avatar component is a wrapper around an internal image or a given icon.
  - or might have to introduce `<ListItemAvatar />` parent to mimic
- Scrolling
  - devs will be able mimic the [max-height MUI demo](https://material-ui.com/components/menus/#max-height-menus) to set that, if it's not automatically cutoff by available space, and it will scroll as it does.

### Moving forward

Current Menu implementation is a poor guesstimation between a dropdown and select menu -- it should be completely replaced. The DropdownMenu and DropdownMenuItem can definitely be ported for an immediate starting point, and then re-implemented with a very simple wrapper around Menu / MenuItem that accesses the Dropdown context for developer ease

**Comment by WilliamKelley** [comment]
Looking more into the [MUI List component(s)](https://material-ui.com/components/lists), that's actually probably where we want to be making most of our thematic changes given that [MenuItem is a ListItem with custom behavior](https://github.com/mui-org/material-ui/blob/latest/packages/material-ui/src/MenuItem/MenuItem.js).

It also seems like AutoComplete may not be required if `MenuItem` can handle [taking a Checkbox as a primary or secondary](https://material-ui.com/components/lists/#checkbox) action and it not violating DOM rules (like how a checkbox input can't appear as a descendant of an option element) -- this will require experimentation since that ListItem demo is in the context of a list, not a Select which will be the use case for us.

@ssbittle Could you visit the Lists demo linked above
- compare the initial paragraph stating it's intention compared to that of the Menus dem
- I think it could be valuable to rename most of Menu / MenuItem to List and ListItem, so that it can be specifically reused in things like Sidebar navigation or data display of a list. 
- Then, a Menu is just the popover / elevated off the page version of a List, and a MenuItem is maybe even exactly the same from a design view, or however it may turn out.
