### ISSUE TITLE
SparkThemeProvider is overriding body font size to 0.875rem

### ISSUE THREAD

**Issue by slingner** [prenda-school/prenda-spark#78]
![image](https://user-images.githubusercontent.com/56003456/123145988-452cdd00-d412-11eb-9717-1121b0763050.png)

Working on implementing the new Navbar into Prenda World and noticed that when wrapping the Navbar with the SparkThemeProvider, the font size for the body is being overwritten. Adding an `!important` to the body in main.less in Prenda World fixes this, but this seems like a deeper issue. 

Any thoughts on what's happening here? @WilliamKelley

**Comment by WilliamKelley** [comment]
This isn't so much an issue with Spark as it is a side-effect of I think JSS and the styling engine that Material-UI advantages. 

When I first used MUI in Code Club, I had a weird interaction between the LESS file `body`/`main` font size declarations when the `ThemeProvider` was added to the DOM. It was weird because Material-UI didn't actually inject a different font-size, but something just didn't play nice. It'll take some debugging to see what the solution is -- for Code Club it was correcting the LESS file value.

Is your work live anywhere that I can dig around in?

**Comment by WilliamKelley** [comment]
Forgot to say, it's not an issue with Spark because we don't set a custom value for `body` / `main` font-size. We use the browser's default, which is best a11y practice.

**Comment by slingner** [comment]
Thanks for the quick reply, I have a branch `sl-navbar` in Prenda World now, with the Navbar happening in `imports/ui/Header.tsx `(excuse all of the commented out code, focused on getting the Spark import in first before bringing in all of the other Header functionality). 

The `styles/main.less` file is where the body styles are being set.

**Comment by slingner** [comment]
I also was attempting to import some of the new icons in this branch, but Seigler had mentioned that they have not been fully published to Spark yet?

**Comment by WilliamKelley** [comment]
Okay I'll take a look after my next meeting. I'll try to be in spatial then and message you if you're available.

The new icons were included in v0.7.3 which is published on NPM. Though I met with Mikey yesterday and he had trouble upgrading because NPM complained about a missing package.json. I couldn't reproduce this on a new project however. Open an issue if you encounter that same error.

You also may run into an issue using the icons detailed in #73 concerning Meteor and bundling all the icons, be wary.

**Comment by WilliamKelley** [comment]
Looks like I was wrong, MUI does inject
```css
body {
  font-size: 0.875rem;
}
```
I'll submit a fix.

**Comment by slingner** [comment]
MuiCssBaseline is overriding the default "Nunito" font-family as well to `  font-family: "Roboto", "Helvetica", "Arial", sans-serif;
`. I

**Comment by WilliamKelley** [comment]
Funny enough MUI v5 changes their injection back to 1rem, https://next.material-ui.com/guides/migration-v4/#cssbaseline
